language: python
python: '3.6'

script: |
  python << "EOF"
  import os
  from librus import LibrusSession
  session = LibrusSession()
  session.login(os.environ['LIBRUS_USERNAME'], os.environ['LIBRUS_PASSWORD'])
  EOF
